[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "the_hangman_wordlist_TheBiemGamer"
version = "0.4"
authors = [
  { name="TheBiemGamer", email="47662596+TheBiemGamer@users.noreply.github.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/TheBiemGamer/TheHangmanWordlist"
Issues = "https://github.com/TheBiemGamer/TheHangmanWordlist/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/the_hangman_wordlist_TheBiemGamer"]